import type { EvidenceItem, LossFormEntry, ScenarioCanvas, TreatmentOption, UncertaintyItem } from '../types'

const makeId = () => crypto.randomUUID()

export const lossFormCatalog: Array<{ type: string; description: string }> = [
  { type: 'Productivity loss', description: 'Lost staff time, manual workarounds, delayed work, downtime.' },
  { type: 'Response cost', description: 'Investigation, incident response, recovery labor, consultants, overtime.' },
  { type: 'Replacement cost', description: 'Hardware, software, vendor replacement, rebuilds, restored services.' },
  { type: 'Fines and judgments', description: 'Regulatory penalties, legal settlements, contractual penalties.' },
  { type: 'Reputation damage', description: 'Lost trust, customer attrition, public credibility impact.' },
  { type: 'Competitive advantage loss', description: 'Strategic delay, lost market position, opportunity cost.' },
]

export const makeLossForms = (): LossFormEntry[] =>
  lossFormCatalog.map((item) => ({
    id: makeId(),
    type: item.type,
    selected: false,
    low: null,
    typical: null,
    high: null,
    notes: '',
    evidenceSource: '',
  }))

export const createEmptyCanvas = (): ScenarioCanvas => ({
  id: makeId(),
  title: 'Decision-Ready Risk Scenario Canvas',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  vagueRiskPhrase: '',
  insufficientBecause: '',
  domain: '',
  decisionType: '',
  decisionQuestion: '',
  decisionOwner: '',
  decisionDeadline: '',
  businessObjective: '',
  asset: '',
  event: '',
  effect: '',
  stakeholders: [],
  scenarioStatement: '',
  frequencyRange: { p5: null, p50: null, p95: null, rationale: '', confidence: '', dataQuality: '' },
  magnitudeRange: {
    p5: null,
    p50: null,
    p95: null,
    rationale: '',
    confidence: '',
    dataQuality: '',
    unknownDollarValues: false,
  },
  lossForms: makeLossForms(),
  mostImportantLossDriver: '',
  tailRiskDriver: '',
  evidenceSources: [],
  uncertaintyItems: [],
  treatmentOptions: [],
  legacyHeatmapRating: '',
  heatmapPrimaryConcern: 'unknown',
  heatmapDecisionContext: '',
  recommendation: '',
  manualSummaryOverride: '',
  summaryMode: 'executive',
  reviewer: '',
  reviewDate: '',
  reviewSignoffNotes: '',
  revisionHistory: [],
})

function lossFormsPreset(
  entries: Array<{
    type: string
    selected: boolean
    low: number | null
    typical: number | null
    high: number | null
    notes: string
    evidenceSource: string
  }>,
): LossFormEntry[] {
  return lossFormCatalog.map(({ type }) => {
    const hit = entries.find((e) => e.type === type)
    if (hit) {
      return {
        id: makeId(),
        type,
        selected: hit.selected,
        low: hit.low,
        typical: hit.typical,
        high: hit.high,
        notes: hit.notes,
        evidenceSource: hit.evidenceSource,
      }
    }
    return {
      id: makeId(),
      type,
      selected: false,
      low: null,
      typical: null,
      high: null,
      notes: '',
      evidenceSource: '',
    }
  })
}

function ev(p: Partial<EvidenceItem> & Pick<EvidenceItem, 'sourceType' | 'sourceName' | 'supports' | 'quality'>): EvidenceItem {
  return {
    id: makeId(),
    sourceDate: '',
    basisOfEstimate: '',
    smeRole: '',
    notes: '',
    ...p,
  }
}

function unc(p: Omit<UncertaintyItem, 'id'>): UncertaintyItem {
  return { id: makeId(), ...p }
}

function tr(p: Partial<TreatmentOption> & Pick<TreatmentOption, 'optionName' | 'category'>): TreatmentOption {
  return {
    id: makeId(),
    estimatedCost: null,
    expectedEffect: 'Reduces frequency',
    narrativeNotes: '',
    implementationDifficulty: 'medium',
    timeHorizon: '0-3 months',
    confidence: 'medium',
    ...p,
  }
}

const buildExample = (seed: Partial<ScenarioCanvas>): ScenarioCanvas => ({
  ...createEmptyCanvas(),
  ...seed,
  updatedAt: new Date().toISOString(),
})

const baseExamples = [
  buildExample({
    vagueRiskPhrase: 'Legacy platform risk remains elevated.',
    insufficientBecause:
      'It hides which platform and workload, what failure mode matters, and what recovery and customer-impact assumptions sit behind the label.',
    decisionType: 'Modernize',
    decisionQuestion: 'Should we fund additional monitoring and recovery automation for a critical batch workflow?',
    domain: 'Legacy systems',
    asset: 'Nightly claims adjudication batch workflow',
    event: 'Batch processing failure',
    effect: 'Delayed downstream processing, manual reconciliation, overtime, and service disruption',
    scenarioStatement:
      'Because nightly batch processing failure affects claims/payment operations, the organization may experience delayed downstream processing, manual reconciliation, overtime, and service disruption, requiring a decision about recovery investment.',
    frequencyRange: { p5: 0.25, p50: 1, p95: 4, rationale: 'Past outage and failure events show occasional spikes.', confidence: 'medium', dataQuality: 'moderate' },
    magnitudeRange: { p5: 25000, p50: 150000, p95: 1200000, rationale: 'Based on overtime, delay cost, and escalations.', confidence: 'medium', dataQuality: 'moderate', unknownDollarValues: false },
    stakeholders: ['Operations', 'Finance', 'Customers / members'],
  }),
  buildExample({
    vagueRiskPhrase: 'Privileged access risk is high.',
    insufficientBecause:
      'It hides which accounts and paths are in scope, what change scenarios are material, and how exceptions translate into business impact beyond audit language.',
    decisionType: 'Mitigate',
    decisionQuestion: 'Should we prioritize privileged access remediation on the legacy platform before other IAM work?',
    domain: 'Identity and access',
    asset: 'Critical transaction processing platform',
    event: 'Excessive privileged access and unauthorized change potential',
    effect: 'Data integrity issues, audit findings, and operational disruption',
    scenarioStatement:
      'Because excessive privileged access affects a critical transaction platform, the organization may experience unauthorized changes, data integrity issues, audit findings, or operational disruption, requiring a decision about remediation sequencing.',
    frequencyRange: { p5: 0.05, p50: 0.2, p95: 1, rationale: 'Based on review exceptions and change anomalies.', confidence: 'low', dataQuality: 'moderate' },
    magnitudeRange: { p5: 50000, p50: 500000, p95: 5000000, rationale: 'Potential for legal and operational spillover.', confidence: 'low', dataQuality: 'weak', unknownDollarValues: false },
    stakeholders: ['Legal / compliance', 'Executives', 'Operations'],
  }),
  buildExample({
    vagueRiskPhrase: 'AI governance risk requires attention.',
    insufficientBecause:
      'It hides which workflow and decision points use model output, what human review is supposed to catch, and what go-live evidence the business already has versus what is still assumed.',
    decisionType: 'Monitor',
    decisionQuestion:
      'Should we allow an AI-assisted operational workflow into production before additional human review controls are implemented?',
    decisionOwner: 'Chief Risk Officer (delegate: Operations Risk Lead)',
    decisionDeadline: '2026-06-30',
    businessObjective:
      'Scale regulated workflow assistance without increasing undetected erroneous decisions, rework, or supervisory findings.',
    domain: 'AI governance',
    asset: 'Regulated operational workflow with AI-generated recommendations',
    event: 'AI output used without adequate review controls',
    effect: 'Erroneous decisions, compliance issues, and audit defensibility gaps',
    scenarioStatement:
      'Because AI-generated recommendations affect a regulated operational workflow, the organization may experience erroneous decisions, rework, compliance issues, customer impact, or audit defensibility gaps, requiring a decision about go-live controls.',
    frequencyRange: { p5: 1, p50: 6, p95: 24, rationale: 'Pilot variance and incident analogs show recurring risk.', confidence: 'medium', dataQuality: 'weak' },
    magnitudeRange: { p5: 5000, p50: 75000, p95: 800000, rationale: 'Estimate combines remediation labor and potential penalties.', confidence: 'medium', dataQuality: 'weak', unknownDollarValues: false },
    stakeholders: ['Customers / members', 'Legal / compliance', 'Executives'],
    lossForms: lossFormsPreset([
      {
        type: 'Productivity loss',
        selected: true,
        low: 15000,
        typical: 65000,
        high: 280000,
        notes: 'Rework, manual checks, and customer communication after incorrect recommendations.',
        evidenceSource: 'Pilot incident log and SME time study',
      },
      {
        type: 'Response cost',
        selected: true,
        low: 25000,
        typical: 120000,
        high: 420000,
        notes: 'Investigation, model review, legal read-in, and control redesign.',
        evidenceSource: 'IR retainer quotes and internal labor rates',
      },
      {
        type: 'Fines and judgments',
        selected: true,
        low: 0,
        typical: 95000,
        high: 620000,
        notes: 'Tail reflects supervisory scrutiny and customer remediation scenarios.',
        evidenceSource: 'Compliance counsel scenario desk review',
      },
    ]),
    mostImportantLossDriver: 'Productivity loss and response cost from undetected bad recommendations before controls mature.',
    tailRiskDriver: 'Fines and judgments if a control miss maps to customer harm and regulatory escalation.',
    evidenceSources: [
      ev({
        sourceType: 'internal',
        sourceName: 'Pilot quality metrics and override rate dashboard',
        supports: 'frequency',
        quality: 'moderate',
        notes: '12-week pilot; spike weeks correlate with model drift and staffing gaps.',
        basisOfEstimate: 'Aggregated pilot tickets and QA sampling',
        sourceDate: '2026-04-01',
      }),
      ev({
        sourceType: 'external',
        sourceName: 'Public enforcement summaries for similar regulated workflows',
        supports: 'scenario plausibility',
        quality: 'weak',
        notes: 'Analogs, not direct precedent for this product line.',
        basisOfEstimate: 'External scan of three comparable cases',
        sourceDate: '2026-03-15',
      }),
      ev({
        sourceType: 'sme',
        sourceName: 'Model validation lead',
        supports: 'magnitude',
        quality: 'moderate',
        notes: 'Judgment on tail tied to depth of human review and exception handling.',
        basisOfEstimate: 'Structured SME workshop with documented assumptions',
        smeRole: 'Model risk / validation',
      }),
    ],
    uncertaintyItems: [
      unc({
        keyUncertainty: 'Production incident rate once volume exceeds pilot by 5x.',
        uncertaintyType: 'Data gap',
        reducibleByResearch: 'Yes',
        wouldChangeDecision: 'Yes',
        researchAction: 'Shadow-mode run with parallel human-only path for 30 days; compare defect rates.',
        owner: 'Operations Risk Lead',
        notes: 'If defect rate holds, go-live timing could move earlier.',
        decisionImpact: 'high',
        researchEffort: 'medium',
      }),
      unc({
        keyUncertainty: 'Human review catch rate under peak-season staffing.',
        uncertaintyType: 'Control effectiveness unknown',
        reducibleByResearch: 'Maybe',
        wouldChangeDecision: 'Maybe',
        researchAction: 'Sampled re-review study; define minimum staffing model.',
        owner: 'Compliance Testing',
        notes: 'May shift preferred treatment toward delay versus narrowed scope.',
        decisionImpact: 'medium',
        researchEffort: 'low',
      }),
    ],
    treatmentOptions: [
      tr({
        optionName: 'Delay production go-live; add staged human-in-the-loop checkpoints',
        category: 'Mitigate',
        estimatedCost: 185000,
        expectedEffect: 'Reduces magnitude',
        narrativeNotes: 'Adds latency but materially reduces undetected erroneous decisions during learning period.',
        implementationDifficulty: 'medium',
        timeHorizon: '3-6 months',
        confidence: 'high',
      }),
      tr({
        optionName: 'Narrow scope to non-regulated subset of workflow',
        category: 'Avoid',
        estimatedCost: 45000,
        expectedEffect: 'Reduces frequency',
        narrativeNotes: 'Reduces exposure surface while building evidence on the harder slice.',
        implementationDifficulty: 'low',
        timeHorizon: '0-3 months',
        confidence: 'medium',
      }),
      tr({
        optionName: 'Go-live with enhanced monitoring and weekly control testing',
        category: 'Monitor',
        estimatedCost: 95000,
        expectedEffect: 'Improves evidence',
        narrativeNotes: 'Keeps timeline but increases assurance burden; needs explicit capacity plan.',
        implementationDifficulty: 'medium',
        timeHorizon: '0-3 months',
        confidence: 'medium',
      }),
    ],
    legacyHeatmapRating: 'High (Yellow)',
    heatmapPrimaryConcern: 'magnitude',
    heatmapDecisionContext: 'Go-live decision for AI-assisted regulated workflow with incomplete production-scale defect history.',
    recommendation:
      'Prefer delaying full go-live until shadow-mode results and minimum staffing for human review are evidenced, unless scope is narrowed to a clearly non-regulated subset with signed supervisory alignment.',
    reviewer: 'J. Flack',
    reviewDate: '2026-05-01',
    reviewSignoffNotes:
      'Residual uncertainty on peak staffing catch rate; quarterly control test and executive read-out required before expanding model scope.',
  }),
  buildExample({
    vagueRiskPhrase: 'Third-party processing risk remains high.',
    insufficientBecause:
      'It hides which vendor and interfaces, contractual recovery expectations, and how monthly peaks change customer and settlement impact.',
    decisionType: 'Mitigate',
    decisionQuestion: 'Should we require stronger recovery controls from a critical payment vendor this quarter?',
    domain: 'Third party',
    asset: 'Vendor-hosted payment processing dependency',
    event: 'Sustained third-party outage during monthly peak volume',
    effect: 'Backlog growth, delayed settlements, and customer escalations',
    scenarioStatement:
      'Because third-party outage affects payment processing, the organization may experience delayed settlements, manual fallback workload, and customer impact, requiring a decision about contractual and resilience controls.',
    frequencyRange: { p5: 0.1, p50: 0.6, p95: 2, rationale: 'Past incidents and status-page history indicate periodic disruption.', confidence: 'medium', dataQuality: 'moderate' },
    magnitudeRange: { p5: 40000, p50: 220000, p95: 1800000, rationale: 'Blend of overtime, service credits, and revenue timing impacts.', confidence: 'medium', dataQuality: 'moderate', unknownDollarValues: false },
    stakeholders: ['Operations', 'Finance', 'Vendors'],
  }),
  buildExample({
    vagueRiskPhrase: 'Cloud misconfiguration risk is medium-high.',
    insufficientBecause:
      'It hides which workloads are internet-facing, which misconfiguration classes matter here, and how drift findings tie to plausible exposure paths.',
    decisionType: 'Escalate',
    decisionQuestion: 'Should we escalate funding for preventive cloud configuration guardrails?',
    domain: 'Cloud',
    asset: 'Internet-facing cloud workload and configuration baseline',
    event: 'Storage or network policy misconfiguration',
    effect: 'Data exposure potential, rapid incident response demand, and audit exceptions',
    scenarioStatement:
      'Because cloud configuration drift affects internet-facing workloads, the organization may experience exposure events, response costs, and compliance risk, requiring a decision about preventive controls funding.',
    frequencyRange: { p5: 0.5, p50: 3, p95: 10, rationale: 'Drift findings and remediation volume suggest recurring events.', confidence: 'medium', dataQuality: 'strong' },
    magnitudeRange: { p5: 15000, p50: 120000, p95: 950000, rationale: 'Response labor and possible notification/legal costs dominate.', confidence: 'medium', dataQuality: 'moderate', unknownDollarValues: false },
    stakeholders: ['Legal / compliance', 'Operations', 'Executives'],
  }),
  buildExample({
    vagueRiskPhrase: 'Resilience posture for claims remains uncertain.',
    insufficientBecause:
      'It hides dependency topology, realistic recovery time for intake, and how backlog clearing translates into customer harm and financial timing.',
    decisionType: 'Fund / invest',
    decisionQuestion: 'Should we invest in active-active resilience for claims intake services?',
    decisionOwner: 'VP Operations (Sponsor: CIO)',
    decisionDeadline: '2026-07-15',
    businessObjective:
      'Protect member-facing claims intake during regional disruption without over-investing in duplicate capacity.',
    domain: 'Resilience / continuity',
    asset: 'Claims intake API and queueing pipeline',
    event: 'Regional cloud service disruption',
    effect: 'Claims intake delays, manual queueing, and policy-service disruption',
    scenarioStatement:
      'Because regional disruption affects claims intake services, the organization may experience customer delays and manual operations, requiring a decision about active-active resilience investment.',
    frequencyRange: { p5: 0.05, p50: 0.3, p95: 1.2, rationale: 'Regional events are infrequent but not negligible.', confidence: 'low', dataQuality: 'moderate' },
    magnitudeRange: { p5: 100000, p50: 650000, p95: 4200000, rationale: 'High-end outcomes include sustained outage and backlog clearing.', confidence: 'medium', dataQuality: 'weak', unknownDollarValues: false },
    stakeholders: ['Customers / members', 'Operations', 'Finance'],
    lossForms: lossFormsPreset([
      {
        type: 'Productivity loss',
        selected: true,
        low: 80000,
        typical: 420000,
        high: 2100000,
        notes: 'Manual intake, call center surge, and backlog clearing labor.',
        evidenceSource: 'BCP tabletop labor model',
      },
      {
        type: 'Replacement cost',
        selected: true,
        low: 120000,
        typical: 380000,
        high: 1600000,
        notes: 'Failover capacity, vendor premium support, and temporary routing.',
        evidenceSource: 'Architecture review and vendor quotes',
      },
      {
        type: 'Reputation damage',
        selected: true,
        low: 0,
        typical: 180000,
        high: 1200000,
        notes: 'Member complaints, regulatory inquiry risk, and service credits.',
        evidenceSource: 'Customer ops and complaints analytics',
      },
    ]),
    mostImportantLossDriver: 'Productivity loss from sustained manual intake and backlog clearing during regional outage.',
    tailRiskDriver: 'Replacement cost and reputation if disruption exceeds assumed recovery window.',
    evidenceSources: [
      ev({
        sourceType: 'internal',
        sourceName: 'Regional outage tabletop outcomes (last 18 months)',
        supports: 'frequency',
        quality: 'moderate',
        notes: 'Infrequent events; severe tail anchored to dependency assumptions.',
        basisOfEstimate: 'Facilitated tabletop with ops and claims SMEs',
        sourceDate: '2026-02-10',
      }),
      ev({
        sourceType: 'internal',
        sourceName: 'Claims intake dependency map and RTO worksheet',
        supports: 'scenario plausibility',
        quality: 'strong',
        notes: 'Documents single-region choke points and manual fallback limits.',
        basisOfEstimate: 'Architecture review sign-off package',
        sourceDate: '2026-03-22',
      }),
      ev({
        sourceType: 'sme',
        sourceName: 'Claims operations director',
        supports: 'magnitude',
        quality: 'moderate',
        notes: 'Calibrated high-end backlog clearing and member impact duration.',
        basisOfEstimate: 'SME workshop with historical surge weeks',
        smeRole: 'Business operations',
      }),
    ],
    uncertaintyItems: [
      unc({
        keyUncertainty: 'Whether active-active materially reduces member-impacting minutes versus warm standby plus runbook hardening.',
        uncertaintyType: 'Recovery assumption',
        reducibleByResearch: 'Yes',
        wouldChangeDecision: 'Yes',
        researchAction: 'Vendor-proved failover drill with measured member-facing metrics.',
        owner: 'Resilience engineering',
        notes: 'If gains are thin, funding case shifts to cheaper hardening path.',
        decisionImpact: 'high',
        researchEffort: 'high',
      }),
      unc({
        keyUncertainty: 'True peak-season concurrency versus test assumptions.',
        uncertaintyType: 'Data gap',
        reducibleByResearch: 'Maybe',
        wouldChangeDecision: 'Maybe',
        researchAction: 'Load trace analysis on last three peak months.',
        owner: 'Capacity planning',
        notes: 'Could widen magnitude band if peaks exceed modeled queue depth.',
        decisionImpact: 'medium',
        researchEffort: 'medium',
      }),
    ],
    treatmentOptions: [
      tr({
        optionName: 'Fund active-active intake with automated traffic steering',
        category: 'Mitigate',
        estimatedCost: 2400000,
        expectedEffect: 'Improves recovery',
        narrativeNotes: 'Highest capital; strongest reduction in member-impacting outage minutes if dependencies cooperate.',
        implementationDifficulty: 'high',
        timeHorizon: '6-12 months',
        confidence: 'medium',
      }),
      tr({
        optionName: 'Invest in warm standby plus hardened runbooks and staffing surge model',
        category: 'Mitigate',
        estimatedCost: 620000,
        expectedEffect: 'Reduces magnitude',
        narrativeNotes: 'Cheaper; residual tail remains if regional outage exceeds RTO.',
        implementationDifficulty: 'medium',
        timeHorizon: '3-6 months',
        confidence: 'medium',
      }),
      tr({
        optionName: 'Defer major resilience spend one cycle; accept explicit backlog risk',
        category: 'Defer',
        estimatedCost: 80000,
        expectedEffect: 'Does not materially reduce exposure',
        narrativeNotes: 'Buys budget room but requires explicit board-level risk acceptance language.',
        implementationDifficulty: 'low',
        timeHorizon: 'Immediate',
        confidence: 'high',
      }),
    ],
    legacyHeatmapRating: 'Medium-High (Yellow)',
    heatmapPrimaryConcern: 'frequency',
    heatmapDecisionContext: 'Resilience funding trade-off for claims intake during credible regional disruption.',
    recommendation:
      'If member-impacting minutes are the primary risk appetite driver, pursue funded failover drills before committing to active-active; if drills show unacceptable tail, prioritize active-active scope reduction (subset of intake) over full deferral.',
    reviewer: 'J. Flack',
    reviewDate: '2026-05-02',
    reviewSignoffNotes: 'Executive forum to confirm acceptable tail given competitive pressure on claims service levels.',
  }),
  buildExample({
    vagueRiskPhrase: 'Audit evidence latency remains elevated.',
    insufficientBecause:
      'It hides which controls slip, where evidence breaks in the workflow, and what attestation delay costs in labor and audit confidence.',
    decisionType: 'Modernize',
    decisionQuestion: 'Should we modernize evidence capture to reduce control assurance lag?',
    domain: 'Data governance',
    asset: 'Control evidence collection and attestation workflow',
    event: 'Delayed or incomplete evidence retrieval',
    effect: 'Late attestations, rework, and increased control uncertainty',
    scenarioStatement:
      'Because delayed evidence capture affects control assurance workflows, the organization may experience attestation delays and audit friction, requiring a decision about modernization scope.',
    frequencyRange: { p5: 2, p50: 8, p95: 20, rationale: 'Recurring late evidence requests across review cycles.', confidence: 'high', dataQuality: 'strong' },
    magnitudeRange: { p5: 5000, p50: 45000, p95: 280000, rationale: 'Impacts dominated by labor, remediation projects, and delayed sign-off.', confidence: 'high', dataQuality: 'moderate', unknownDollarValues: false },
    stakeholders: ['Legal / compliance', 'Executives', 'Operations'],
  }),
  buildExample({
    vagueRiskPhrase: 'Legacy IAM onboarding risk persists.',
    insufficientBecause:
      'It hides which identity stores feed IBM i, how long excessive access persists, and what unauthorized change scenarios are actually plausible.',
    decisionType: 'Mitigate',
    decisionQuestion: 'Should we prioritize automated joiner/mover/leaver controls for IBM i access?',
    domain: 'IBM i / midrange',
    asset: 'Privileged and operational account lifecycle process',
    event: 'Late deprovisioning or excessive access carryover',
    effect: 'Unauthorized activity potential and audit findings',
    scenarioStatement:
      'Because IAM lifecycle gaps affect IBM i access governance, the organization may experience prolonged excessive access and control exceptions, requiring a decision about automation priority.',
    frequencyRange: { p5: 1, p50: 4, p95: 12, rationale: 'Quarterly access reviews repeatedly identify stale privileges.', confidence: 'medium', dataQuality: 'moderate' },
    magnitudeRange: { p5: 25000, p50: 180000, p95: 1400000, rationale: 'Tail includes unauthorized change with compliance consequences.', confidence: 'medium', dataQuality: 'moderate', unknownDollarValues: false },
    stakeholders: ['Legal / compliance', 'Operations', 'Executives'],
  }),
  buildExample({
    vagueRiskPhrase: 'Mainframe continuity risk needs attention.',
    insufficientBecause:
      'It hides which settlement chains break, what recovery-time objectives are credible, and what contractual and regulatory pressure exists if DR modernization slips.',
    decisionType: 'Defer',
    decisionQuestion: 'Can we safely defer DR modernization for one more fiscal cycle?',
    decisionOwner: 'Head of Mainframe Operations (CFO co-decision)',
    decisionDeadline: '2026-05-30',
    businessObjective:
      'Balance cash preservation with credible recovery for settlement-critical batch if a major disruption occurs.',
    domain: 'Mainframe',
    asset: 'Mainframe batch scheduling and settlement processing',
    event: 'Extended recovery-time miss during major disruption',
    effect: 'Settlement delays, SLA breaches, and executive escalation',
    scenarioStatement:
      'Because recovery-time misses affect mainframe settlement workflows, the organization may experience financial delay and compliance pressure, requiring a decision about deferment versus modernization.',
    frequencyRange: { p5: 0.02, p50: 0.1, p95: 0.5, rationale: 'Low annual likelihood with severe operational implications.', confidence: 'low', dataQuality: 'weak' },
    magnitudeRange: { p5: 150000, p50: 900000, p95: 9000000, rationale: 'Severe case includes prolonged outage and contractual penalties.', confidence: 'low', dataQuality: 'weak', unknownDollarValues: false },
    stakeholders: ['Finance', 'Operations', 'Executives'],
    lossForms: lossFormsPreset([
      {
        type: 'Productivity loss',
        selected: true,
        low: 200000,
        typical: 1200000,
        high: 5200000,
        notes: 'Manual settlement processing, reconciliation armies, and executive war-room time.',
        evidenceSource: 'DR drill after-action and finance SME estimates',
      },
      {
        type: 'Fines and judgments',
        selected: true,
        low: 0,
        typical: 400000,
        high: 3500000,
        notes: 'Contractual penalties and regulatory pressure if settlement windows are missed.',
        evidenceSource: 'Legal review of material contracts',
      },
      {
        type: 'Competitive advantage loss',
        selected: true,
        low: 0,
        typical: 250000,
        high: 1800000,
        notes: 'Strategic delay and reputational harm with large counterparties.',
        evidenceSource: 'Relationship management escalation history',
      },
    ]),
    mostImportantLossDriver: 'Productivity loss and settlement delay costs if recovery-time objectives are missed in a major event.',
    tailRiskDriver: 'Fines and judgments plus counterparty confidence loss in prolonged outage tail.',
    evidenceSources: [
      ev({
        sourceType: 'internal',
        sourceName: 'Last full DR exercise report and recovery-time observations',
        supports: 'frequency',
        quality: 'weak',
        notes: 'Rare events; evidence is thin but directionally consistent with prior misses.',
        basisOfEstimate: 'Single exercise plus partial failover tests',
        sourceDate: '2025-11-05',
      }),
      ev({
        sourceType: 'internal',
        sourceName: 'Vendor DR dependency list and maintenance blackout calendar',
        supports: 'control condition',
        quality: 'moderate',
        notes: 'Shows coupling that can extend recovery even when internal systems are healthy.',
        basisOfEstimate: 'Vendor attestations and ops calendar',
        sourceDate: '2026-03-01',
      }),
      ev({
        sourceType: 'sme',
        sourceName: 'Mainframe operations lead',
        supports: 'magnitude',
        quality: 'moderate',
        notes: 'Tail anchored to worst-case manual settlement duration and interest carry.',
        basisOfEstimate: 'SME scenario walkthrough with finance partner',
        smeRole: 'Platform operations',
      }),
    ],
    uncertaintyItems: [
      unc({
        keyUncertainty: 'Whether stated RTO is achievable under vendor blackout and staffing assumptions used in the last exercise.',
        uncertaintyType: 'Recovery assumption',
        reducibleByResearch: 'Yes',
        wouldChangeDecision: 'Yes',
        researchAction: 'Targeted failover test with measured batch restart and settlement checkpoints.',
        owner: 'DR program manager',
        notes: 'If RTO is not credible, deferral becomes harder to defend.',
        decisionImpact: 'high',
        researchEffort: 'medium',
      }),
      unc({
        keyUncertainty: 'Unbudgeted vendor uplift costs if modernization is accelerated next year.',
        uncertaintyType: 'Financial impact unknown',
        reducibleByResearch: 'Maybe',
        wouldChangeDecision: 'Maybe',
        researchAction: 'Request firm quotes for phased modernization milestones.',
        owner: 'Finance business partner',
        notes: 'Could shift preference between defer and partial fund this cycle.',
        decisionImpact: 'medium',
        researchEffort: 'low',
      }),
    ],
    treatmentOptions: [
      tr({
        optionName: 'Fund minimum modernization package to close top three recovery gaps',
        category: 'Mitigate',
        estimatedCost: 1100000,
        expectedEffect: 'Improves recovery',
        narrativeNotes: 'Reduces tail while preserving most capex for next fiscal year.',
        implementationDifficulty: 'medium',
        timeHorizon: '6-12 months',
        confidence: 'medium',
      }),
      tr({
        optionName: 'Defer DR modernization one cycle with explicit compensating monitoring',
        category: 'Defer',
        estimatedCost: 140000,
        expectedEffect: 'Does not materially reduce exposure',
        narrativeNotes: 'Cheapest near term; requires signed risk acceptance and monitoring commitments.',
        implementationDifficulty: 'low',
        timeHorizon: 'Immediate',
        confidence: 'high',
      }),
      tr({
        optionName: 'Transfer part of tail via insurance / contractual risk sharing where insurable',
        category: 'Transfer',
        estimatedCost: 220000,
        expectedEffect: 'Transfers financial loss',
        narrativeNotes: 'May reduce financial tail but not operational member impact; read policy exclusions carefully.',
        implementationDifficulty: 'medium',
        timeHorizon: '3-6 months',
        confidence: 'low',
      }),
    ],
    legacyHeatmapRating: 'High (Red)',
    heatmapPrimaryConcern: 'control uncertainty',
    heatmapDecisionContext: 'Whether DR modernization can be deferred without breaching credible recovery expectations for settlement.',
    recommendation:
      'Do not defer without a refreshed, measured RTO proof point: either fund the minimum gap-closing package or obtain explicit risk acceptance tied to named compensating controls and a hard revisit date.',
    reviewer: 'J. Flack',
    reviewDate: '2026-05-03',
    reviewSignoffNotes: 'CFO and ops co-sign required if deferral proceeds; legal review of counterparty SLAs attached.',
  }),
  buildExample({
    vagueRiskPhrase: 'Privacy compliance risk remains high.',
    insufficientBecause:
      'It hides which data elements and processes are in scope, what incident shapes trigger notification, and how operational loss couples to legal and brand impact.',
    decisionType: 'Transfer / insure',
    decisionQuestion: 'Should we expand cyber/privacy insurance coverage limits before renewal?',
    domain: 'Privacy',
    asset: 'Customer data handling and retention process',
    event: 'Improper data handling incident',
    effect: 'Regulatory review, legal cost, and brand impact',
    scenarioStatement:
      'Because privacy handling failures affect customer data workflows, the organization may experience regulatory and legal impacts, requiring a decision about transfer strategy and control uplift.',
    frequencyRange: { p5: 0.08, p50: 0.4, p95: 1.8, rationale: 'Historical near-misses and control exceptions indicate periodic exposure.', confidence: 'medium', dataQuality: 'moderate' },
    magnitudeRange: { p5: 80000, p50: 600000, p95: 6500000, rationale: 'Magnitude driven by response, legal, and potential fines.', confidence: 'medium', dataQuality: 'moderate', unknownDollarValues: false },
    stakeholders: ['Legal / compliance', 'Customers / members', 'Executives'],
  }),
  buildExample({
    vagueRiskPhrase: 'Cyber event detect-and-respond risk remains elevated.',
    insufficientBecause:
      'It hides dwell-time assumptions, coverage hours, and what actually changes incident size when detection slips.',
    decisionType: 'Fund / invest',
    decisionQuestion: 'Should we fund 24x7 detection coverage to reduce containment time?',
    domain: 'Cybersecurity',
    asset: 'Security monitoring and incident response operating model',
    event: 'Delayed detection of active compromise',
    effect: 'Expanded incident scope, response cost, and recovery delay',
    scenarioStatement:
      'Because delayed compromise detection affects response operations, the organization may experience larger incidents and higher recovery costs, requiring a decision about monitoring investment.',
    frequencyRange: { p5: 0.2, p50: 1.4, p95: 4.8, rationale: 'Alert backlog and shift coverage gaps increase recurrence probability.', confidence: 'medium', dataQuality: 'moderate' },
    magnitudeRange: { p5: 30000, p50: 260000, p95: 2600000, rationale: 'Tail outcomes reflect longer dwell time and broader restoration.', confidence: 'medium', dataQuality: 'moderate', unknownDollarValues: false },
    stakeholders: ['Operations', 'Legal / compliance', 'Executives'],
  }),
  buildExample({
    vagueRiskPhrase: 'Identity governance analytics coverage is weak.',
    insufficientBecause:
      'It hides which analytics gaps drive attestation misses, how long risky access persists, and what acceptance would explicitly carry into the next quarter.',
    decisionType: 'Accept',
    decisionQuestion: 'Can we accept current analytics gaps for one quarter while foundational data is cleaned?',
    decisionOwner: 'CISO (delegate: IAM program lead)',
    decisionDeadline: '2026-06-15',
    businessObjective:
      'Stabilize identity governance reporting while data cleanup completes, without pretending visibility is stronger than it is.',
    domain: 'Identity and access',
    asset: 'Identity risk analytics and attestation reporting',
    event: 'Insufficient anomaly detection coverage',
    effect: 'Slow issue discovery and prolonged risky access',
    scenarioStatement:
      'Because analytics gaps affect identity governance visibility, the organization may experience delayed issue detection and prolonged exposure, requiring a decision about temporary acceptance versus acceleration.',
    frequencyRange: { p5: 1, p50: 5, p95: 16, rationale: 'Backlog of unresolved attestation anomalies indicates ongoing occurrence.', confidence: 'medium', dataQuality: 'weak' },
    magnitudeRange: { p5: 7000, p50: 65000, p95: 540000, rationale: 'Impacts include rework, audit burden, and potential incident handling.', confidence: 'medium', dataQuality: 'weak', unknownDollarValues: false },
    stakeholders: ['Operations', 'Legal / compliance', 'Executives'],
    lossForms: lossFormsPreset([
      {
        type: 'Productivity loss',
        selected: true,
        low: 4000,
        typical: 28000,
        high: 160000,
        notes: 'Manual attestation rework, helpdesk volume, and delayed remediation starts.',
        evidenceSource: 'IAM operations ticket export',
      },
      {
        type: 'Response cost',
        selected: true,
        low: 5000,
        typical: 42000,
        high: 220000,
        notes: 'Targeted hunts and consultant support when anomalies spike.',
        evidenceSource: 'Security operations staffing model',
      },
      {
        type: 'Fines and judgments',
        selected: true,
        low: 0,
        typical: 0,
        high: 380000,
        notes: 'Tail reflects plausible regulatory friction if issues cluster during audit window.',
        evidenceSource: 'Compliance counsel desk scenario',
      },
    ]),
    mostImportantLossDriver: 'Productivity loss from prolonged risky access while discovery remains slow.',
    tailRiskDriver: 'Response cost and regulatory tail if anomalies cluster during external review.',
    evidenceSources: [
      ev({
        sourceType: 'internal',
        sourceName: 'Attestation anomaly backlog trend',
        supports: 'frequency',
        quality: 'moderate',
        notes: 'Backlog persists; cleanup program underway but incomplete.',
        basisOfEstimate: 'GRC export with 8-quarter history',
        sourceDate: '2026-04-18',
      }),
      ev({
        sourceType: 'internal',
        sourceName: 'Identity data quality remediation plan milestones',
        supports: 'control condition',
        quality: 'weak',
        notes: 'Milestones exist; slippage risk is the key uncertainty for acceptance.',
        basisOfEstimate: 'Program plan v3 with dated deliverables',
        sourceDate: '2026-04-01',
      }),
      ev({
        sourceType: 'sme',
        sourceName: 'IAM program lead',
        supports: 'magnitude',
        quality: 'moderate',
        notes: 'Judgment on rework and incident handling costs if backlog worsens under peak hiring.',
        basisOfEstimate: 'SME estimate with documented assumptions',
        smeRole: 'IAM program',
      }),
    ],
    uncertaintyItems: [
      unc({
        keyUncertainty: 'Whether data cleanup materially improves detection within one quarter.',
        uncertaintyType: 'Data gap',
        reducibleByResearch: 'Yes',
        wouldChangeDecision: 'Yes',
        researchAction: 'Pilot improved correlation rules on cleaned subset; measure time-to-detect.',
        owner: 'IAM engineering',
        notes: 'If pilot fails, acceptance window should shrink or require extra controls.',
        decisionImpact: 'high',
        researchEffort: 'medium',
      }),
      unc({
        keyUncertainty: 'Audit tolerance for continued acceptance language if anomalies do not decline.',
        uncertaintyType: 'Regulatory uncertainty',
        reducibleByResearch: 'Maybe',
        wouldChangeDecision: 'Maybe',
        researchAction: 'Formal read-in with internal audit and compliance testing leads.',
        owner: 'Compliance testing',
        notes: 'May force mitigation spend even if technical cleanup is on track.',
        decisionImpact: 'medium',
        researchEffort: 'low',
      }),
    ],
    treatmentOptions: [
      tr({
        optionName: 'Accept gaps for one quarter with explicit compensating manual reviews',
        category: 'Accept',
        estimatedCost: 120000,
        expectedEffect: 'Does not materially reduce exposure',
        narrativeNotes: 'Cheapest near term; requires tight scope, named owners, and dated exit criteria.',
        implementationDifficulty: 'medium',
        timeHorizon: '0-3 months',
        confidence: 'medium',
      }),
      tr({
        optionName: 'Accelerate analytics uplift project (pull forward vendor deliverables)',
        category: 'Mitigate',
        estimatedCost: 340000,
        expectedEffect: 'Reduces frequency',
        narrativeNotes: 'Improves detection sooner; competes for engineering capacity with other IAM priorities.',
        implementationDifficulty: 'high',
        timeHorizon: '3-6 months',
        confidence: 'medium',
      }),
      tr({
        optionName: 'Narrow acceptance scope to non-privileged populations only',
        category: 'Mitigate',
        estimatedCost: 90000,
        expectedEffect: 'Reduces magnitude',
        narrativeNotes: 'Reduces worst-case exposure while keeping a time-boxed acceptance story credible.',
        implementationDifficulty: 'medium',
        timeHorizon: '0-3 months',
        confidence: 'medium',
      }),
    ],
    legacyHeatmapRating: 'Medium (Yellow)',
    heatmapPrimaryConcern: 'control uncertainty',
    heatmapDecisionContext: 'Time-boxed acceptance of weak analytics coverage during identity data cleanup.',
    recommendation:
      'Accept only with a written uncertainty carry: narrow scope where possible, add compensating manual reviews for privileged paths, and pre-schedule a hard stop review if anomaly backlog does not decline by the agreed date.',
    reviewer: 'J. Flack',
    reviewDate: '2026-05-04',
    reviewSignoffNotes: 'Internal audit concurrence required; attach milestone table and exit criteria to signoff.',
  }),
]

const maturitySequence: Array<ScenarioCanvas['exampleMaturity']> = [
  'early framing',
  'moderate evidence',
  'decision-ready draft',
  'early framing',
  'moderate evidence',
  'decision-ready draft',
  'early framing',
  'moderate evidence',
  'decision-ready draft',
  'early framing',
  'moderate evidence',
  'decision-ready draft',
]

const lessonSequence = [
  'Translate vague language into a single scenario statement tied to a concrete decision.',
  'Separate frequent control exceptions from severe business-impact events.',
  'Use ranges to communicate uncertainty and avoid false precision.',
  'Dependency risk needs explicit evidence from both internal and third-party records.',
  'High recurrence scenarios demand control hygiene and disciplined assumptions.',
  'Low frequency does not mean low consequence; tail effects can dominate.',
  'Operational friction costs are real loss drivers even without major incidents.',
  'Access governance scenarios often require SME judgment to explain exposure pathways.',
  'Rare, severe continuity scenarios require explicit decision trade-offs.',
  'Transfer options can reduce financial impact but may not reduce operational loss.',
  'Detection timing is a frequency and magnitude lever, not just a control status.',
  'Acceptance decisions should clearly state what uncertainty is being carried.',
]

export const exampleScenarios = baseExamples.map((example, index) => ({
  ...example,
  exampleMaturity: maturitySequence[index] ?? 'early framing',
  exampleLesson: lessonSequence[index] ?? 'Scenario framing practice example.',
}))
